spring.application.name=data-processor-api
server.port=8081

#db configurtion
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

#log configuration

# Definir el nivel de log global
logging.level.root=INFO
# Nivel específico para tu paquete de negocio
logging.level.com.tuproyecto.api=DEBUG

# Ruta y nombre del archivo de log
logging.file.name=logs/api-prod-incidents.log
# Patrón de salida (Fecha, Nivel, PID, Hilo, Clase, Mensaje)
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %highlight(%-5level) [%X{correlationId}] %logger{36} - %msg%n
# Patrón de salida para el ARCHIVO (Asegúrate de incluir el correlationId aquí también)
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{correlationId}] %logger{36} - %msg%n