


server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: transaccion-route
          uri: http://localhost:8081  # DESTINO FINAL: Micro con la BD
          predicates:
            - Path=/processortransactionapi/**
          filters:
            - CustomValidationFilter